// Side-effect imports: each template registers itself on import.
// Add a new template by creating a file here and importing it below —
// no switch statement to extend.
import "./summarizeText.js";
import "./extractKeyPoints.js";
import "./decomposeTopic.js";
import "./generateSearchQueries.js";
import "./generateContentionQueries.js";
import "./extractGroundedKeyPoints.js";
import "./synthesizeSubtopic.js";
import "./restructureLayers.js";
import "./depthAuditScore.js";
import "./classifyVolatility.js";
import "./sequenceModules.js";
import "./writeLessonMetadata.js";
import "./generateRecallQuestions.js";
import "./generateApplicationQuestions.js";
import "./generateTransferQuestions.js";
import "./scoreFreeTextAnswer.js";
import "./classifyTopicType.js";
import "./selectPracticeFormat.js";
import "./generateProjectBrief.js";
import "./generateSimulationScenario.js";
import "./generateDebatePrompt.js";
import "./dialogueTurn.js";
import "./critiquePracticeAttempt.js";
import "./generateReflectionPrompt.js";
import "./classifyTopicOrGoal.js";
import "./decomposeGoalIntoPath.js";
import "./determineCrossDomainDependencies.js";
import "./quickRefreshCheck.js";

export * from "./registry.js";
export * from "./summarizeText.js";
export * from "./extractKeyPoints.js";
export * from "./decomposeTopic.js";
export * from "./generateSearchQueries.js";
export * from "./extractGroundedKeyPoints.js";
export * from "./synthesizeSubtopic.js";
export * from "./restructureLayers.js";
export * from "./depthAuditScore.js";
export * from "./classifyVolatility.js";
export * from "./sequenceModules.js";
export * from "./writeLessonMetadata.js";
export * from "./generateRecallQuestions.js";
export * from "./generateApplicationQuestions.js";
export * from "./generateTransferQuestions.js";
export * from "./scoreFreeTextAnswer.js";
export * from "./classifyTopicType.js";
export * from "./selectPracticeFormat.js";
export * from "./generateProjectBrief.js";
export * from "./generateSimulationScenario.js";
export * from "./generateDebatePrompt.js";
export * from "./dialogueTurn.js";
export * from "./critiquePracticeAttempt.js";
export * from "./generateReflectionPrompt.js";
export * from "./classifyTopicOrGoal.js";
export * from "./decomposeGoalIntoPath.js";
export * from "./determineCrossDomainDependencies.js";
export * from "./quickRefreshCheck.js";
